# Tasks 12.17, 12.19, 12.21
version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      #Task 12.12
      - redis_data:/data

  # Task 12.18
  todo-backend-dev:
    image: todo-backend-dev
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis
    build:
      context: ./todo-backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  todo-frontend-dev:
    image: todo-frontend-dev
    container_name: todo-frontend-dev
    build:
      context: ./todo-frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    depends_on:
      - todo-backend-dev
    #ports:
    #  - 3001:3000

  nginx:
    image: nginx:1.20.1
    container_name: proxy_pass
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - todo-frontend-dev # wait for the frontend container to be started

volumes:
  mongo_data:
  redis_data:
