# Task 12.20, 12.22
version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  todo-backend:
    image: todo-backend
    container_name: todo-backend
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    depends_on:
      - todo-backend
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    depends_on:
      - todo-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80

volumes:
  mongo_data:
  redis_data:
