version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  #mongo-express:
  #  image: mongo-express
  #  container_name: mongo-express
  #  restart: always
  #  depends_on:
  #    - mongo
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: "the_username"
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: "the_password"
  #    ME_CONFIG_MONGODB_URL: "mongodb://the_username:the_password@localhost:3456"

  # Task 12.9
  redis:
    image: redis
    container_name: redis
    restart: always
    command: [ 'redis-server', '--appendonly', 'yes' ]
    ports:
      - '6379:6379'
    volumes:
      #Task 12.12
      - redis_data:/data

  #Task 12.16
  todo-backend:
    image: todo-backend
    container_name: todo-backend
    depends_on:
      - mongo
      - redis
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=//redis:6379 # Task 12.9
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

volumes:
  mongo_data:
  redis_data:
